name: Deploy to GitHub Pages

on:
  push:
    branches:
      - actionsfrontend  # Trigger deployment on push to 'actions' branch
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend
      
      - name: List contents of frontend directory for debugging
        run: ls -al ./frontend
        working-directory: ./

      - name: List contents of build directory for debugging
        run: ls -al ./frontend/build
        working-directory: ./

      - name: Upload to artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
